# Generated by Django 3.2.2 on 2021-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.FloatField(default=1),
        ),
    ]
